config/routes.rb
::Refinery::Application.routes.draw do
  resources :pdf_newsletters, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :pdf_newsletters, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base

  acts_as_indexed :fields => [:volume, :issue]

  validates :volume, :presence => true
  validates :issue, :presence => true
  validates :pdf, :presence => true

  belongs_to :pdf, :class_name => 'Resource'

  def month
    self.publish_on.strftime("%B")
  end

  def year
    self.publish_on.year
  end
  scope :published, lambda {
    where("newsletters.publish_on IS NOT NULL AND newsletters.publish_on <= ?", Time.zone.now)
  }

  scope :recent, published.order("newsletters.publish_on DESC")

  def self.current
   self.recent.first
  end
end

app/models/pdf_newsletter.rb
class PdfNewsletter < ActiveRecord::Base

  acts_as_indexed :fields => [:volume, :issue]

  validates :volume, :presence => true
  validates :issue, :presence => true
  validates :pdf, :presence => true

  belongs_to :pdf, :class_name => 'Resource'

  def title
    "#{month} Newsletter"
  end

  def month
    self.publish_on.strftime("%B")
  end

  def year
    self.publish_on.year
  end
  scope :published, lambda {
    where("pdf_newsletters.publish_on IS NOT NULL AND pdf_newsletters.publish_on <= ?", Time.zone.now)
  }

  scope :recent, published.order("pdf_newsletters.publish_on DESC")

  def self.current
   self.recent.first
  end

  def self.whats_new?
    true
  end
end

app/controllers/admin/newsletters_controller.rb
module Admin
  class NewslettersController < Admin::BaseController

    crudify :newsletter,
            :title_attribute => 'volume', :xhr_paging => true

  end
end

app/controllers/admin/pdf_newsletters_controller.rb
module Admin
  class PdfNewslettersController < Admin::BaseController

    crudify :pdf_newsletter,
            :title_attribute => 'publish_on', :xhr_paging => true

  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  before_filter :find_all_newsletters
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @newsletter in the line below:
    present(@page)
  end

  def show
    @newsletter = Newsletter.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @newsletter in the line below:
    present(@page)
  end

protected

  def find_all_newsletters
    @newsletters = Newsletter.recent
  end

  def find_page
    @page = Page.where(:link_url => "/newsletters").first
  end

end

app/controllers/pdf_newsletters_controller.rb
class PdfNewslettersController < ApplicationController

  helper :pdf_newsletters
  before_filter :find_all_newsletters
  before_filter :find_page

  def index
    present(@page)
  end

  def show
    @newsletter = PdfNewsletter.find(params[:id])
    redirect_to @newsletter.pdf.url
  end

protected

  def find_all_newsletters
    @newsletters = PdfNewsletter.recent
  end

  def find_page
    @page = Page.where(:link_url => "/pdf_newsletters").first
  end

end

app/helpers/pdf_newsletters_helper.rb
module PdfNewslettersHelper
  def newsletter_description(newsletter)
    "Volume #{newsletter.volume} Issue #{newsletter.issue} - #{newsletter.month} #{newsletter.year}"
  end

  def each_year(newsletters)
    newsletters_list = newsletters
    newsletter = newsletters_list.shift
    while newsletter.present?
      year_list = []
      @year = newsletter.year
      while newsletter && newsletter.year == @year
        year_list << newsletter
        newsletter = newsletters_list.shift
      end
      yield year_list
    end
  end
end

app/views/admin/pdf_newsletters/_actions.html.erb
<ul>
  <% if Admin::PdfNewslettersController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_pdf_newsletters_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_pdf_newsletter_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::PdfNewslettersController.sortable? and PdfNewsletter.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Pdf Newsletters"),
                 admin_pdf_newsletters_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Pdf Newsletters"),
                 admin_pdf_newsletters_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/pdf_newsletters/_form.html.erb
<%= form_for [:admin, @pdf_newsletter] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @pdf_newsletter,
          :include_object_name => true
        } %>

  <div class='field'>
    <%= f.label :publish_on -%>
    <%= f.date_select :publish_on  -%>
  </div>

  <div class='field'>
    <%= f.label :pdf -%>
    <%= render :partial => "/shared/admin/resource_picker", :locals => {
          :f => f,
          :field => :pdf_id,
          :resource => @pdf_newsletter.pdf,
        } %>
  </div>

  <div class='field'>
    <%= f.label :volume -%>
    <%= f.text_field :volume  -%>
  </div>

  <div class='field'>
    <%= f.label :issue -%>
    <%= f.text_field :issue  -%>
  </div>

  <div class='field'>
    <%= f.label :editor -%>
    <%= f.text_field :editor  -%>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.pdf_newsletters.pdf_newsletter'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @pdf_newsletter.volume)
              } %>
<% end -%>

app/views/admin/pdf_newsletters/_newsletters.html.erb
<%= will_paginate @newsletters %>
<%= render :partial => "sortable_list" %>

app/views/admin/pdf_newsletters/_pdf_newsletter.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(pdf_newsletter) -%>">
  <span class='title'>
    <%= "Volume #{pdf_newsletter.volume}, Issue #{pdf_newsletter.issue} - #{pdf_newsletter.month} #{pdf_newsletter.year}" %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), pdf_newsletter_path(pdf_newsletter),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_pdf_newsletter_path(pdf_newsletter),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_pdf_newsletter_path(pdf_newsletter),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => "Volume #{pdf_newsletter.volume} Issue #{pdf_newsletter.issue}"),
        :method => :delete %>
  </span>
</li>

app/views/admin/pdf_newsletters/_pdf_newsletters.html.erb
<%= will_paginate @pdf_newsletters %>
<%= render :partial => "sortable_list" %>

app/views/admin/pdf_newsletters/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @pdf_newsletters.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'pdf_newsletters' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/pdf_newsletters/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'pdf_newsletter', :collection => @pdf_newsletters %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/pdf_newsletters/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/pdf_newsletters/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::PdfNewslettersController.sortable? and PdfNewsletter.count > 1 %>

app/views/admin/pdf_newsletters/new.html.erb
<%= render :partial => "form" %>

app/views/pdf_newsletters/_list_by_year.html.erb
<% each_year(newsletters) do |year_list| %>
  <h2><%=year_list.first.year-%> Newsletters</h2>
  <% unless year_list.first.editor.blank? %>
    <p>(By Editor <%=year_list.first.editor%>)</p>
  <% end %>
  <ul>
    <% year_list.each do |newsletter| %>
      <li><%= render :partial => 'newsletter', :object => newsletter %></li>
    <% end %>
  </ul>
<% end %>

app/views/pdf_newsletters/_newsletter.html.erb
<%= link_to newsletter_description(newsletter), newsletter.pdf.url %>

app/views/pdf_newsletters/index.html.erb
<% content_for :body_content_left do %>
<%= render :partial => 'list_by_year', :locals => {:newsletters => @newsletters} %>
<% end %>

<%= render :partial => "/shared/content_page" %>